/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;
import static Swing.Erreur.erreur;
import java.awt.Font;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.*;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//import java.sql.SQLException;
//import java.util.Scanner;

/**
 *
 * @author el-barae
 */
public class Stock extends javax.swing.JFrame {
    
    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
        jButton5.setVisible(false);
        jTable1.getTableHeader().setFont(new Font("Lohit Devanagari",Font.BOLD,20));
        setLocation(400, 160);
        tableModel.addColumn("Code Barre");
        tableModel.addColumn("Quantité");
        tableModel.addColumn("Catégorie");
        tableModel.addColumn("Nom Produit");
        tableModel.addColumn("Prix");
        tableModel.addColumn("Prix Initial");
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock" , "root" , "1234abcD.");
            Statement statement = conn.createStatement();
            String query = "SELECT * FROM stock_product";
            ResultSet res = statement.executeQuery(query);
             while (res.next()) {
                    
                    int q=res.getInt("quantity");
                    Object[] rowData = {
                            res.getString("codebarre"),
                            q,
                            res.getString("type"),
                            res.getString("nom"),
                            res.getFloat("prix"),
                            res.getFloat("prix_ini")
                        };
                    if(q<=10){
                        jButton5.setVisible(true);
                    }
                    tableModel.addRow(rowData);
             }
                 
             System.out.println("la table est a remplir ...");
            conn.close();
        } catch (Exception ex) {
            
            System.out.println("erreur: "+ex);
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            Erreur.erreur = sw.toString();
            new Erreur(null,true).show();
        }
        jTable1.setModel(tableModel);
    }
    boolean ok=true;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jLabel1.setText("Code bar");

        jLabel2.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jLabel2.setText("Quantité");

        jLabel3.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jLabel3.setText("Categorie");

        jLabel4.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jLabel4.setText("Nom produit");

        jLabel5.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jLabel5.setText("Prix");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Lohit Devanagari", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODE BAR", "PRODUIT", "QUANTITE", "CATEGORIE", "PRIX", "PRIX INITIAL"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionForeground(new java.awt.Color(255, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jLabel6.setText("Prix initial");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jLabel7.setText("Chercher");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("-");
        jButton4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 0));
        jButton5.setText("Quantity < 10");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Supprimer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 204, 0));
        jButton7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Modifier");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton2)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock" , "root" , "1234abcD.");
        String codebarre=jTextField1.getText();
        String query = "SELECT * FROM stock_product WHERE codebarre = ?";
        PreparedStatement statement = conn.prepareStatement(query);
        statement.setString(1,codebarre);
        ResultSet res = statement.executeQuery();
        if(res.next()){
            jTextField3.setText(res.getString("type"));
            jTextField4.setText(res.getString("nom"));
            jTextField5.setText(Float.toString(res.getFloat("prix")));
            jTextField6.setText(Float.toString(res.getFloat("prix_ini")));
        }
        
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Acceuil a = new Acceuil();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                String codebarre =jTextField1.getText();
                final String codebarre1 =jTextField1.getText();
                String categorie =jTextField3.getText();
                String nomproduit =jTextField4.getText();
                Float prix = Float.valueOf(jTextField5.getText());
                Float prix_initial = Float.valueOf(jTextField6.getText());
                Integer quantity = Integer.valueOf(jTextField2.getText());
                Float P=0.0f;
                Float Pi=0.0f;
                int att=0;             
                boolean chp=false;
        int quantite = Integer.parseInt(jTextField2.getText());
        PreparedStatement pst;
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock" , "root" , "1234abcD.");
            PreparedStatement pst1;
            PreparedStatement stm = con.prepareStatement("SELECT prix, prix_ini, en_attend FROM stock_product WHERE codebarre = ?");
                    stm.setString(1,codebarre);
                    ResultSet res1 = stm.executeQuery();
                    while (res1.next()) {
                            chp=true;
                            P = res1.getFloat("prix");
                            Pi = res1.getFloat("prix_ini");
                            att = res1.getInt("en_attend");
                            att=att+1;
                    }
            if((chp==true) && (!Objects.equals(prix, P) || !Objects.equals(prix_initial, Pi))){
                String query3 = "UPDATE stock_product SET en_attend = ? WHERE codebarre = ?";
                PreparedStatement stm2 = con.prepareStatement(query3);
                stm2.setInt(1, att);
                stm2.setString(2,codebarre);
                stm2.executeUpdate();
                pst1 = con.prepareStatement("INSERT INTO stock_product (codebarre,quantity,type,nom,prix,prix_ini,en_attend) VALUES (?, ?, ?, ?, ?, ?, ?)");
                pst1.setString(1, String.valueOf(att));
                pst1.setInt(2, quantity);
                pst1.setString(3, categorie);
                pst1.setString(4, nomproduit);
                pst1.setFloat(5, prix);
                pst1.setFloat(6, prix_initial);
                pst1.setInt(7, 0);
                pst1.executeUpdate();
                tableModel.setRowCount(0);
                    Statement st = con.createStatement();
                    String query = "SELECT * FROM stock_product";
                    ResultSet res = st.executeQuery(query);
                    while (res.next()) {
                    Object[] rowData = {
                            res.getString("codebarre"),
                            res.getInt("quantity"),
                            res.getString("type"),
                            res.getString("nom"),
                            res.getFloat("prix"),
                            res.getFloat("prix_ini")
                        };
                    tableModel.addRow(rowData);
                    }
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                chp=false;
            }
            else{
            /*tableModel.setRowCount(0);
                    Statement st = con.createStatement();
                    String query = "SELECT * FROM stock_product";
                    ResultSet res = st.executeQuery(query);
                    while (res.next()) {
                    Object[] rowData = {
                            res.getString("codebarre"),
                            res.getInt("quantity"),
                            res.getString("type"),
                            res.getString("nom"),
                            res.getFloat("prix"),
                            res.getFloat("prix_ini")
                        };
                    tableModel.addRow(rowData);
                    }
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");*/
                PreparedStatement statement = con.prepareStatement("SELECT * FROM stock_product WHERE codebarre = ?");
                statement.setString(1,codebarre);
                ResultSet result = statement.executeQuery();
                System.out.println("SQL Select query ");
                if(result.next()){
                    PreparedStatement smt = con.prepareStatement("UPDATE stock_product SET quantity = quantity + ? WHERE codebarre = ?");
                    smt.setInt(1, quantite);
                    smt.setString(2, codebarre);
                    smt.executeUpdate();
                    tableModel.setRowCount(0);
                    Statement stmt = con.createStatement();
                    String query5 = "SELECT * FROM stock_product";
            
                    ResultSet res5 = stmt.executeQuery(query5);
                    while (res5.next()) {
                    Object[] rowData = {
                            res5.getString("codebarre"),
                            res5.getInt("quantity"),
                            res5.getString("type"),
                            res5.getString("nom"),
                            res5.getFloat("prix"),
                            res5.getFloat("prix_ini")
                        };
                    tableModel.addRow(rowData);
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    }
                    System.out.println("Update Table ");
                    con.close();
               
                }
                else{
                Object[] rowData = {codebarre, quantite, categorie, nomproduit, prix, prix_initial};
                tableModel.addRow(rowData);
                pst = con.prepareStatement("INSERT INTO stock_product (codebarre,quantity,type,nom,prix,prix_ini,en_attend) VALUES (?, ?, ?, ?, ?, ?, ?)");
                pst.setString(1, codebarre);
                pst.setInt(2, quantite);
                pst.setString(3, categorie);
                pst.setString(4, nomproduit);
                pst.setFloat(5, prix);
                pst.setFloat(6, prix_initial);
                pst.setInt(7, 0);
                pst.executeUpdate();
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                System.out.println("SQL Insert query: " );
                con.close();
                }
            }
        } catch (Exception ex) {
            
            System.out.println("erreur: "+ex);
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            Erreur.erreur = sw.toString();
            new Erreur(null,true).show();
        }
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        String nomProduit =jTextField7.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock" , "root" , "1234abcD.");
            if ("".equals(nomProduit)){
                    tableModel.setRowCount(0);
                    Statement st = con.createStatement();
                    String query = "SELECT * FROM stock_product";
            
                    ResultSet res = st.executeQuery(query);
                    while (res.next()) {
                    Object[] rowData = {
                            res.getString("codebarre"),
                            res.getInt("quantity"),
                            res.getString("type"),
                            res.getString("nom"),
                            res.getFloat("prix"),
                            res.getFloat("prix_ini")
                        };
                    tableModel.addRow(rowData);
                    }
            }
            else{
                PreparedStatement statement = con.prepareStatement("SELECT * FROM stock_product WHERE nom = ?");
                statement.setString(1,nomProduit);
                ResultSet result = statement.executeQuery();
                System.out.println("SQL Select query ");
                tableModel.setRowCount(0);
                while(result.next()){
                    Object[] rowData = {
                            result.getString("codebarre"),
                            result.getInt("quantity"),
                            result.getString("type"),
                            result.getString("nom"),
                            result.getFloat("prix"),
                            result.getFloat("prix_ini")
                        };
                    tableModel.addRow(rowData);
                }
            }
        }catch (Exception ex) {
            
            System.out.println("erreur: "+ex);
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            Erreur.erreur = sw.toString();
            new Erreur(null,true).show();
        }
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock" , "root" , "1234abcD.");
            Statement statement = conn.createStatement();
            if(ok==true){
            jButton5.setText("Stock");
            tableModel.setRowCount(0);
            String query = "SELECT * FROM stock_product WHERE quantity < 10";
            ResultSet res = statement.executeQuery(query);
             while (res.next()) {
                    int q=res.getInt("quantity");
                    Object[] rowData = {
                            res.getString("codebarre"),
                            q,
                            res.getString("type"),
                            res.getString("nom"),
                            res.getFloat("prix"),
                            res.getFloat("prix_ini")
                        };
                    tableModel.addRow(rowData);
             }
                ok=false; 
             System.out.println("la table est a remplir ...");
            }else{
                jButton5.setText("Quantity < 10");
                tableModel.setRowCount(0);
                String query1 = "SELECT * FROM stock_product";
            ResultSet res = statement.executeQuery(query1);
             while (res.next()) {
                    
                    int q=res.getInt("quantity");
                    Object[] rowData = {
                            res.getString("codebarre"),
                            q,
                            res.getString("type"),
                            res.getString("nom"),
                            res.getFloat("prix"),
                            res.getFloat("prix_ini")
                        };
                    if(q<=10){
                        jButton5.setVisible(true);
                    }
                    tableModel.addRow(rowData);
                }
                ok=true;
            }
            conn.close();
        } catch (Exception ex) {
            
            System.out.println("erreur: "+ex);
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            Erreur.erreur = sw.toString();
            new Erreur(null,true).show();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int[] selectedRows = jTable1.getSelectedRows();
        String codebarre;
        String nom;
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock" , "root" , "1234abcD.");
                for (int i = selectedRows.length - 1; i >= 0; i--) {
                    codebarre = (String) jTable1.getValueAt(selectedRows[i], 0); 
                    nom = (String) jTable1.getValueAt(selectedRows[i], 3);
                    tableModel.removeRow(selectedRows[i]);
                    String query1 = "DELETE FROM stock_product WHERE codebarre = ?";
                    PreparedStatement smt = conn.prepareStatement(query1);
                    smt.setString(1,codebarre);
                    smt.executeUpdate();
                    /*String query2 = "UPDATE stock_product SET en_attend = en_attend-1 WHERE nom = ?";
                    PreparedStatement smt1 = conn.prepareStatement(query2);
                    smt1.setString(1,nom);
                    smt1.executeUpdate();*/
                }
        } catch (Exception ex) {
            
            System.out.println("erreur: "+ex);
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            Erreur.erreur = sw.toString();
            JOptionPane.showMessageDialog(this, erreur, "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow(); // Obtenez la ligne sélectionnée
                if (row >= 0) {
                    // Remplissez les champs texte avec les valeurs de la ligne sélectionnée
                    jTextField1.setText(tableModel.getValueAt(row, 0).toString());
                    jTextField2.setText(tableModel.getValueAt(row, 1).toString());
                    jTextField3.setText(tableModel.getValueAt(row, 2).toString());
                    jTextField4.setText(tableModel.getValueAt(row, 3).toString());
                    jTextField5.setText(tableModel.getValueAt(row, 4).toString());
                    jTextField6.setText(tableModel.getValueAt(row, 5).toString());
                }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        try {
            String codebarre =jTextField1.getText();
                String categorie =jTextField3.getText();
                String nomproduit =jTextField4.getText();
                Float prix = Float.valueOf(jTextField5.getText());
                Float prix_initial = Float.valueOf(jTextField6.getText());
                Integer quantity = Integer.valueOf(jTextField2.getText());
                Float P=0.0f;
                Float Pi=0.0f;
                int att=0;
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stock" , "root" , "1234abcD.");
            PreparedStatement statement = con.prepareStatement("UPDATE stock_product SET nom = ?, type = ?  WHERE codebarre = ?");
            statement.setString(1,nomproduit);
            statement.setString(2,categorie);
            statement.setString(3,codebarre);
            int resultat = statement.executeUpdate();
            PreparedStatement pst;
            PreparedStatement stm = con.prepareStatement("SELECT prix, prix_ini, en_attend FROM stock_product WHERE codebarre = ?");
                    stm.setString(1,codebarre);
                    ResultSet res1 = stm.executeQuery();
                    while (res1.next()) {
                            P = res1.getFloat("prix");
                            Pi = res1.getFloat("prix_ini");
                            att = res1.getInt("en_attend");
                            att=att+1;
                    }
            if(prix!=P || prix_initial!=Pi){
                String query3 = "UPDATE stock_product SET en_attend = ? WHERE codebarre = ?";
                PreparedStatement stm2 = con.prepareStatement(query3);
                stm2.setInt(1, att);
                stm2.setString(2,codebarre);
                stm2.executeUpdate();
                pst = con.prepareStatement("INSERT INTO stock_product (codebarre,quantity,type,nom,prix,prix_ini,en_attend) VALUES (?, ?, ?, ?, ?, ?, ?)");
                pst.setString(1, String.valueOf(att));
                pst.setInt(2, quantity);
                pst.setString(3, categorie);
                pst.setString(4, nomproduit);
                pst.setFloat(5, prix);
                pst.setFloat(6, prix_initial);
                pst.setInt(7, 0);
                pst.executeUpdate();
            }else{
                String query2 = "UPDATE stock_product SET quantity = quantity + ? WHERE codebarre = ?";
                PreparedStatement stm1 = con.prepareStatement(query2);
                stm1.setInt(1,quantity);
                stm1.setString(2,codebarre);
                stm1.executeUpdate();
            }
            tableModel.setRowCount(0);
                    Statement st = con.createStatement();
                    String query = "SELECT * FROM stock_product";
                    ResultSet res = st.executeQuery(query);
                    while (res.next()) {
                    Object[] rowData = {
                            res.getString("codebarre"),
                            res.getInt("quantity"),
                            res.getString("type"),
                            res.getString("nom"),
                            res.getFloat("prix"),
                            res.getFloat("prix_ini")
                        };
                    tableModel.addRow(rowData);
                    }
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
            System.out.println("produit a ete supprimer ");
            
            
        } catch (NumberFormatException | SQLException ex) {
            
            System.out.println("erreur: "+ex);
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            Erreur.erreur = sw.toString();
         JOptionPane.showMessageDialog(this, erreur, "Erreur", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }
    DefaultTableModel tableModel = new DefaultTableModel();

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
